# Generated by Django 2.0.6 on 2018-06-27 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_auto_20180627_2132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalnote',
            old_name='users',
            new_name='user',
        ),
    ]
